{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "gogs.labels" . | nindent 4 }}
  name: {{ include "gogs.name" . }}-allow-service-ingress
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingress:
    - ports:
      - port: {{ .Values.service.port }}
        protocol: TCP
  podSelector:
    matchLabels:
      {{- include "gogs.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}