# Default values for gogs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gogs/gogs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

# These values are used to populate the gogs app.ini (config)
# Commonly used values have been templated with Helm, additional values/configuration can be added using 'extras'
# For more information about these values see: https://github.com/gogs/gogs/blob/main/conf/app.ini
gogsConfig:
  server:
    externalUrl: "http://gogs.local/"
  database:
    # The database backend, either "postgres", "mysql" "sqlite3" or "mssql".
    type: sqlite3
    host: 127.0.0.1:5432
    name: gogs
    user: gogs
    password: ''
    # For "sqlite3" only, make sure to use absolute path.
    path: data/gogs.db
  security:
    # !!CHANGE THIS TO KEEP YOUR USER DATA SAFE!!
    secretKey: '!#@FDEWREWR&*('
    # A comma separated list of hostnames that are explicitly allowed to be accessed within the local network.
    # For local webhooks to work you need to add the host(s) or '*' here see: https://github.com/gogs/gogs/discussions/7048
    localNetworkAllowList: ""

  # Supports adding additional items to the app.ini file
  extras: |
    ; Put your additional gogs configuration items here...

probes:
  startup:
    # 20
    initialDelaySeconds: 30
    # Default failureThreshold is 3
    failureThreshold: 3
  liveness:
    # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
    periodSeconds: 30
    # Default failureThreshold is 3
    failureThreshold: 3

volumes:
  - name: data
    emptyDir: {}
  - name: logs
    emptyDir: {}

volumeMounts:
  - mountPath: "/app/gogs/log"
    name: logs

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # The most secure setting which still allow the container to run
  # Unfortunately these setting still violates PodSecurity "restricted:latest"
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  # The container runs a 'chown' over its' data files which will fail if not running as root
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 3000

networkPolicy:
  # Creates a NetworkPolicy which allows ingress to the Gogs pod via the service port (3000)
  create: true

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gogs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
   requests:
#     cpu: 500m
     # If the memory is too limited the gogs will container will restart when dealing with big repos
     memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
